# ASETOOLS 

## Description:
This package ...

## Installation

As simple as 

`pip install git+https://github.com/manuelarcer/asetools.git`

or

`pip install git+git@github.com:manuelarcer/asetools.git`

### Requirements

- pandas
- numpy
- ase
- matplotlib

## Extra content

Extra conent can be found in the folder 'extra', within package's folder.

### 1. vasp_outcar_parser.py

This is a file to fix one of the bugs while reading an OUTCAR file generated by VASP 6. This has been apparent elsewhere (https://gitlab.com/ase/ase/-/issues/1119). I had the same issue. 

The fix was submitted here 
https://gitlab.com/ase/ase/-/commit/9e9234a785c97ca3d49a0f3fca4fec2bdc52eb2b

And the full file can be found in this other page
https://gitlab.com/ase/ase/-/blob/9e9234a785c97ca3d49a0f3fca4fec2bdc52eb2b/ase/io/vasp_parsers/vasp_outcar_parsers.py


  
